// Generated by Wrangler on Sun Jul 21 2024 12:46:12 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	GOOGLE_CLIENT_ID: "633602123635-hbc51bb46ku1qtvqjval60jqv24rk863.apps.googleusercontent.com";
	GOOGLE_CLIENT_SECRET: "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";
	GOOGLE_REDIRECT_URI: "http://localhost:5173/googleredirect";
	R2: R2Bucket;
	DB: D1Database;
}
